### ISSUE TITLE
building with triton support? 

### ISSUE THREAD

**Issue by ngam** [conda-forge/pytorch-cpu-feedstock#166]
- I am a bit confused what is depending on what. As far as I can see, pytorch depends on torchtriton, which in turn seems to depend on pytorch. 
- Is there any difference between torchtriton and triton?
- We already package an old version of triton in conda-forge and have a PR open for version 2.0.0 (https://github.com/conda-forge/triton-feedstock/pull/2). Would this 2.0.0 version be suitable as dependency for here?

_Originally posted by @Tobias-Fischer in https://github.com/conda-forge/pytorch-cpu-feedstock/issues/165#issuecomment-1496605649_

--

More background: #151

**Comment by Tobias-Fischer** [comment]
The first code snippet is an easy example: https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html

**Comment by Tobias-Fischer** [comment]
I just confirmed that this example works: https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html
when using https://github.com/conda-forge/triton-feedstock/pull/3 and installing the cxx_compiler :)

**Comment by Tobias-Fischer** [comment]
Ah, something surprising (?): It also works without installing triton, just by having a `cxx_compiler` installed (e.g. `mamba install compilers`)

**Comment by Tobias-Fischer** [comment]
Made some progress - see https://github.com/conda-forge/triton-feedstock/pull/6

The open question in my mind is still the circular dependency from both torch to triton and from triton to torch. Not sure how to best deal with it .. a `run_constrained` maybe?

**Comment by h-vetinari** [comment]
> Not sure how to best deal with it .. a `run_constrained` maybe?

Probably with a `-base` package that's built here, depended on by triton to build itself, and then we can include triton here as a dependence of the complete `pytorch` package.

**Comment by Tobias-Fischer** [comment]
We need https://github.com/conda-forge/triton-feedstock/pull/6

**Comment by RaulPPelaez** [comment]
Anecdotal experience, but pytorch and triton from conda-forge seem to pick up each other fine today (as in no segfaults when calling torch.compile with the inductor backend). I believe special care should be taken with dependency versions. Both triton and support for it in torch are really experimental and probably have quite narrow ranges of versions where they are supposed to work together.
On a side note, what we would really like to see is pytorch 2.0.1 (available in the pytorch channel) in conda-forge.

**Comment by cread** [comment]
Has anyone looked at this again recently?

**Comment by danpetry** [comment]
Here's what we've done at Anaconda for v2.3.0: https://github.com/AnacondaRecipes/triton-feedstock

There are some notes in the meta.yaml about various choices we made. Let me know if you've got any questions.

**Comment by mgorny** [comment]
I'm going to try making a new pull request for 3.1.0, as that's the version required by PyTorch 2.5.1.

@danpetry, thanks. Curious enough, I've just tried diffing the PyPI 3.1.0 package against the one provided by PyTorch, and — at least as far as `.py` files go — they seem the same. So I don't think we technically need a rename here.

**Comment by danpetry** [comment]
I probably need to re-check the logic of that statement, but that's the conclusion I came to when I worked on it, at least I wanted to be cautious and say, "this should not be used except with pytorch, with which it has been explicitly integration tested"

**Comment by danpetry** [comment]
It uses llvm at runtime, rather than build time

**Comment by isuruf** [comment]
The issue was that triton did not have wheels and even when it did it took time to get releases in. There was also an issue with rocm support not getting merged. All of these have been resolved I think.

**Comment by danpetry** [comment]
ok, so we can now use the wheels rather than the git repo to build?

**Comment by danpetry** [comment]
I think my key issue was that they weren't tagging commits in the github repo, there weren't any sdists, and I didn't want to release a github commit and call it a release version

**Comment by mgorny** [comment]
> I think my key issue was that they weren't tagging commits in the github repo, there weren't any sdists, and I didn't want to release a github commit and call it a release version

Yes, that is still the case. However, they do release versioned wheels, and I've confirmed that the contents of `.py` files match the commit from PyTorch — and I think that's as good confirmation as we can get that it's the commit used to make the release upstream.

**Comment by isuruf** [comment]
@atalman, since you seem to be a maintainer of `triton` on PyPI, could you let us know which commit you use for the wheel relases?

**Comment by danpetry** [comment]
It's [here](https://github.com/pytorch/pytorch/blob/main/.ci/docker/ci_commit_pins/triton.txt) AFAIU, but NB that triton still don't have this tagged

**Comment by danpetry** [comment]
whether that's good enough re traceability for conda-forge, I don't know. for anaconda main, we decided it wasn't. Triton can force-push the branch it's on and remove the commit - and indeed have in the past. (I suppose they can change tags too. Ideal is a github release.)

**Comment by isuruf** [comment]
@danpetry that's for `torch-triton`. AFAIK @atalman manages `triton` on PyPI index in addition to `torch-triton` on pytorch's wheel index..

**Comment by danpetry** [comment]
I believe it's one and the same commit, co-ordinated by him, but he can confirm

**Comment by mgorny** [comment]
The commit fixing compatibility with LLVM 19 is openai/triton@46550ab18e8f7314107cf591b9cf902b290fd45d. I'm going to see how much would we actually need to patch to get it to work on top of 3.1.0.

**Comment by mgorny** [comment]
I've pushed my WIP to https://github.com/conda-forge/triton-feedstock/pull/26.

**Comment by danpetry** [comment]
Worth bearing in mind that LLVM is only used by triton at runtime, to compile cuda kernels. So, keeping it vendored-in isn't an issue so far as compatibility with the rest of the distro is concerned, I think.

**Comment by danpetry** [comment]
I don't know if anyone else can confirm this?

**Comment by mgorny** [comment]
I think the bigger issue here is that triton either downloads a prebuilt LLVM version if it detects a supported platform, or uses system LLVM (expecting this specific commit) when it doesn't.

**Comment by danpetry** [comment]
There's a [smoke test](https://github.com/pytorch/builder/blob/5354a64887c5c4ea4dbf91ac97fcb58bfa273e8a/test/smoke_test/smoke_test.py#L251C24-L251C30) which tests torch.compile with cuda (if an environment variable is appropriately set)

**Comment by mgorny** [comment]
Thanks. Looks like I was wrong and some patching is necessary for regular CC to be able to find CUDA headers:

</details>

```
Testing smoke_test_compile for cuda and torch.float16
/tmp/tmp_itxw3hv/main.c:1:10: fatal error: cuda.h: No such file or directory
    1 | #include "cuda.h"
      |          ^~~~~~~~
compilation terminated.
/tmp/tmpwwhx19wm/main.c:1:10: fatal error: cuda.h: No such file or directory
    1 | #include "cuda.h"
      |          ^~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/output_graph.py", line 1446, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/repro/after_dynamo.py", line 129, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/__init__.py", line 2234, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/compile_fx.py", line 1521, in compile_fx
    return aot_autograd(
           ^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/backends/common.py", line 72, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_functorch/aot_autograd.py", line 1071, in aot_module_simplified
    compiled_fn = dispatch_and_compile()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_functorch/aot_autograd.py", line 1056, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_functorch/aot_autograd.py", line 522, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_functorch/aot_autograd.py", line 759, in _create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
                               ^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 179, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/compile_fx.py", line 1350, in fw_compiler_base
    return _fw_compiler_base(model, example_inputs, is_inference)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/compile_fx.py", line 1421, in _fw_compiler_base
    return inner_compile(
           ^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/compile_fx.py", line 475, in compile_fx_inner
    return wrap_compiler_debug(_compile_fx_inner, compiler_name="inductor")(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/repro/after_aot.py", line 85, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/compile_fx.py", line 661, in _compile_fx_inner
    compiled_graph = FxGraphCache.load(
                     ^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/codecache.py", line 1334, in load
    compiled_graph = compile_fx_fn(
                     ^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/compile_fx.py", line 570, in codegen_and_compile
    compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/compile_fx.py", line 878, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/graph.py", line 1913, in compile_to_fn
    return self.compile_to_module().call
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/graph.py", line 1839, in compile_to_module
    return self._compile_to_module()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/graph.py", line 1845, in _compile_to_module
    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
                                                             ^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/graph.py", line 1784, in codegen
    self.scheduler.codegen()
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/scheduler.py", line 3383, in codegen
    return self._codegen()
           ^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/scheduler.py", line 3461, in _codegen
    self.get_backend(device).codegen_node(node)
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/codegen/cuda_combined_scheduling.py", line 80, in codegen_node
    return self._triton_scheduling.codegen_node(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/codegen/simd.py", line 1155, in codegen_node
    return self.codegen_node_schedule(node_schedule, buf_accesses, numel, rnumel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/codegen/simd.py", line 1364, in codegen_node_schedule
    src_code = kernel.codegen_kernel()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/codegen/triton.py", line 2661, in codegen_kernel
    **self.inductor_meta_common(),
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_inductor/codegen/triton.py", line 2532, in inductor_meta_common
    "backend_hash": torch.utils._triton.triton_hash_with_backend(),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/utils/_triton.py", line 53, in triton_hash_with_backend
    backend = triton_backend()
              ^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/utils/_triton.py", line 45, in triton_backend
    target = driver.active.get_current_target()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/triton/runtime/driver.py", line 23, in __getattr__
    self._initialize_obj()
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/triton/runtime/driver.py", line 20, in _initialize_obj
    self._obj = self._init_fn()
                ^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/triton/runtime/driver.py", line 9, in _create_driver
    return actives[0]()
           ^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/triton/backends/nvidia/driver.py", line 371, in __init__
    self.utils = CudaUtils()  # TODO: make static
                 ^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/triton/backends/nvidia/driver.py", line 80, in __init__
    mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "cuda_utils")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/triton/backends/nvidia/driver.py", line 57, in compile_module_from_src
    so = _build(name, src_path, tmpdir, library_dirs(), include_dir, libraries)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/triton/runtime/build.py", line 48, in _build
    ret = subprocess.check_call(cc_cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/mgorny/.conda/envs/pytorch/bin/x86_64-conda-linux-gnu-cc', '/tmp/tmpwwhx19wm/main.c', '-O3', '-shared', '-fPIC', '-o', '/tmp/tmpwwhx19wm/cuda_utils.cpython-312-x86_64-linux-gnu.so', '-lcuda', '-L/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/triton/backends/nvidia/lib', '-L/lib/x86_64-linux-gnu', '-L/lib32', '-I/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/triton/backends/nvidia/include', '-I/tmp/tmpwwhx19wm', '-I/home/mgorny/.conda/envs/pytorch/include/python3.12']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mgorny/smoke_test.py", line 352, in <module>
    main()
  File "/home/mgorny/smoke_test.py", line 348, in main
    smoke_test_cuda(options.package, options.runtime_error_check, options.torch_compile_check)
  File "/home/mgorny/smoke_test.py", line 171, in smoke_test_cuda
    smoke_test_compile("cuda" if torch.cuda.is_available() else "cpu")
  File "/home/mgorny/smoke_test.py", line 261, in smoke_test_compile
    x_pt2 = torch.compile(foo)(x)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 465, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py", line 1269, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py", line 1064, in __call__
    result = self._inner_convert(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py", line 526, in __call__
    return _compile(
           ^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py", line 924, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py", line 666, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_utils_internal.py", line 87, in wrapper_function
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py", line 699, in _compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/bytecode_transformation.py", line 1322, in transform_code_object
    transformations(instructions, code_options)
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py", line 219, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py", line 634, in transform
    tracer.run()
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/symbolic_convert.py", line 2796, in run
    super().run()
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/symbolic_convert.py", line 983, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/symbolic_convert.py", line 895, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/symbolic_convert.py", line 2987, in RETURN_VALUE
    self._return(inst)
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/symbolic_convert.py", line 2972, in _return
    self.output.compile_subgraph(
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/output_graph.py", line 1117, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/output_graph.py", line 1369, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/output_graph.py", line 1416, in call_user_compiler
    return self._call_user_compiler(gm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/torch/_dynamo/output_graph.py", line 1465, in _call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
CalledProcessError: Command '['/home/mgorny/.conda/envs/pytorch/bin/x86_64-conda-linux-gnu-cc', '/tmp/tmpwwhx19wm/main.c', '-O3', '-shared', '-fPIC', '-o', '/tmp/tmpwwhx19wm/cuda_utils.cpython-312-x86_64-linux-gnu.so', '-lcuda', '-L/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/triton/backends/nvidia/lib', '-L/lib/x86_64-linux-gnu', '-L/lib32', '-I/home/mgorny/.conda/envs/pytorch/lib/python3.12/site-packages/triton/backends/nvidia/include', '-I/tmp/tmpwwhx19wm', '-I/home/mgorny/.conda/envs/pytorch/include/python3.12']' returned non-zero exit status 1.

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

```
</details>

**Comment by amjames** [comment]
@rgommers Thanks!


> Some manual testing seems to confirm success at the "build and seems to compile stuff with nvcc" level - perhaps you have some suggestions into what subset of the PyTorch test suite to run to confirm that PyTorch + Triton works as designed?

What kind of time-limits are we working with? Full coverage is probably a non-starter, but the [inductor tests](https://github.com/pytorch/pytorch/tree/main/test/inductor) will be the best place to focus on. 

I would start with:
- [test_torchindcutor.py](https://github.com/pytorch/pytorch/tree/main/test/inductor/test_torchinductor.py) Which will broadly check codegen 
- [test_max_autotune.py](https://github.com/pytorch/pytorch/tree/main/test/inductor/test_max_autotune.py) will cover many of the custom kernel templates we use in the compiler backend.
- [test_flex_attention.py](https://github.com/pytorch/pytorch/tree/main/test/inductor/test_flex_atention.py) Is probably the most sophisticated way pytorch+triton interact right now. 

Some of these tests will require a specific GPU like A100, but in general the tests should be annotated to skip if they have special requirements like that which are not met.

**Comment by mgorny** [comment]
The plot thickens. After fixing the path errors, I'm getting:

```
RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/tmp_at1jgs8.ptx, line 5; fatal   : Unsupported .version 8.6; current version is '8.5'
ptxas fatal   : Ptx assembly aborted due to errors
```

My guess would be that it doesn't support CUDA 12.6 for some reason. But 12.0 is too old, and I don't think we can cleanly do 12.5 just for Triton without changing PyTorch. Will try to figure out a good solution tomorrow, but I'd appreciate any hints.

**Comment by Tobias-Fischer** [comment]
Are you sure it’s not picking up your system CUDA (12.5?) and then competing against conda CUDA (12.6?)

**Comment by danpetry** [comment]
It might be a problem that the feedstock uses `cuda-nvcc` in the run section directly, instead of `compiler('cuda')` with the activation scripts.  https://github.com/conda-forge/triton-feedstock/blob/7f07922287846f050f2c65f4cfced35f1e1b311d/recipe/meta.yaml#L66

**Comment by mgorny** [comment]
Actually, it turns out we need one more upstream patch for CUDA 12.6 support. But I also need to fix path search, I'll make a pull request later.

> It might be a problem that the feedstock uses `cuda-nvcc` in the run section directly, instead of `compiler('cuda')` with the activation scripts. https://github.com/conda-forge/triton-feedstock/blob/7f07922287846f050f2c65f4cfced35f1e1b311d/recipe/meta.yaml#L66

Hmm, is that actually wrong? I didn't think `compiler('cuda')` actually implies `cuda-nvcc` too, but I can remove that if it's redundant.

**Comment by danpetry** [comment]
AFAIU `compiler('cuda')` resolves to cuda-nvcc_<platform>, partly because of [this setting here](https://github.com/conda-forge/triton-feedstock/blob/7f07922287846f050f2c65f4cfced35f1e1b311d/.ci_support/linux_64_python3.10.____cpython.yaml#L11)

But `cuda-nvcc` [pulls in](https://github.com/conda-forge/cuda-nvcc-feedstock/blob/4731c843f5132f327282c43498bd5cf500ed1315/recipe/meta.yaml#L27) `cuda-nvcc_<platform>` anyway, so the [activation scripts](https://github.com/conda-forge/cuda-nvcc-feedstock/blob/4731c843f5132f327282c43498bd5cf500ed1315/recipe/activate.sh#L55) should be running.

Maybe it's to do with the "conda-build" conditional in the link above, so the I/L flags aren't being added?

**Comment by mgorny** [comment]
Already solved via https://github.com/conda-forge/triton-feedstock/pull/28. Just wondering if I should update the dependencies while at it.

**Comment by Tobias-Fischer** [comment]
@mgorny - does any more work need to be done here?

**Comment by mgorny** [comment]
The remaining question is: do we want to add a requirement from PyTorch to Triton, so that it's pulled in automatically? Unless I'm mistaken, Conda doesn't have "recommends" kind of requirements, so it probably have to be unconditional (and then it would create a cycle).

**Comment by rgommers** [comment]
On PyPI, `triton` has only one dependency (`filelock`) and `torch` depends on `triton`. That sounds about right to me. I don't understand why `triton` in conda-forge has the reverse runtime dependency on `pytorch =*=cuda*`. 

> The remaining question is: do we want to add a requirement from PyTorch to Triton

That would be desirable, but only for `cuda` builds - and I'm not sure that that is possible? If not, then it seems best to leave out the dependency.

**Comment by mgorny** [comment]
> On PyPI, `triton` has only one dependency (`filelock`) and `torch` depends on `triton`. That sounds about right to me. I don't understand why `triton` in conda-forge has the reverse runtime dependency on `pytorch =*=cuda*`.

Well, at least of `triton`'s Python modules do `import torch`, so I guess it's at least an optional dependency.

> > The remaining question is: do we want to add a requirement from PyTorch to Triton
> 
> That would be desirable, but only for `cuda` builds - and I'm not sure that that is possible? If not, then it seems best to leave out the dependency.

Yes, that should be fine.

**Comment by rgommers** [comment]
> Well, at least of `triton`'s Python modules do `import torch`, so I guess it's at least an optional dependency.

There's a bunch of `import torch` in tests and examples, but only one outside of that, which is not at the top level:

https://github.com/triton-lang/triton/blob/f8b5301a92459199e1b9faf7aadf1a7c10bb9866/python/triton/backends/driver.py#L37-L41

So it's optional at most. It's also possible to use Triton with JAX: https://jax.readthedocs.io/en/latest/pallas/design/design.html#lowering-pallas-to-triton-for-gpu. So it looks to me like the dependency in the triton feedstock should be removed. I don't know why it was added in the first place though.

**Comment by hmaarrfk** [comment]
Likely for the tests. 

I agree it can be removed!

Thanks looking into it!

**Comment by mgorny** [comment]
Okay, I'll look into it tomorrow. I also think I'm ready to give rattler-build in pytorch another try!

**Comment by hmaarrfk** [comment]
> Okay, I'll look into it tomorrow. I also think I'm ready to give rattler-build in pytorch another try!

Lets try to give the windows folk a break on the rebasing.

They seem pretty close, and the new resources in the form of CIs make it finally a possibility.

Given that pytorch build times are dominated by mathematical compilation, I don't see much of an advantage in working on this immediately

**Comment by mgorny** [comment]
> > Okay, I'll look into it tomorrow. I also think I'm ready to give rattler-build in pytorch another try!
> 
> Lets try to give the windows folk a break on the rebasing.

Sure, I'll wait.

> Given that pytorch build times are dominated by mathematical compilation, I don't see much of an advantage in working on this immediately

Well, just for the record, it would make my local dev builds faster, since (with an up-to-date ccache available) conda-build is actually being a bottleneck :-).

**Comment by hmaarrfk** [comment]
> Well, just for the record, it would make my local dev builds faster, since (with an up-to-date ccache available) conda-build is actually being a bottleneck :-).

Interesting..... 

I know your working on alot, but I would be willing to learn if you can document your process of getting ccache working with conda-forge's isolated builds!

My strategy is currently to follow a variant of https://github.com/conda-forge/tensorflow-feedstock/issues/360

**Comment by mgorny** [comment]
Right, I suppose it makes sense to add it to the README as well. Basically, I'm running `conda build ...` directly, and PyTorch's CMake simply picks up `ccache` from my host root. Hardly a clean solution but it just happened to work here.

Oh, I'm passing `--no-build-id --croot /var/tmp/conda-bld` to get caches to match. And `~/.config/ccache/ccache.conf` of:

```
compiler_check=none
compression=true
sloppiness=pch_defines,time_macros
hash_dir=false
base_dir=/var/tmp/conda-bld
max_size = 6G
```

I'll document that when I update some pull request next.
